In [99]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import KFold, train_test_split, cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn import svm, datasets
import plotly.express as px
from sklearn .ensemble import RandomForestClassifier
from sklearn .ensemble import VotingClassifier , BaggingClassifier , StackingClassifier


In [100]:
from google.colab import files
files.upload()

Saving new_model.csv to new_model (1).csv


{'new_model (1).csv': b'Bp,Sg,Al,Su,Rbc,Bu,Sc,Sod,Pot,Hemo,Wbcc,Rbcc,Htn,Class\r\n80.0,1.02,1.0,0.0,1.0,36.0,1.2,137.53,4.63,15.4,7800.0,5.2,1.0,1\r\n50.0,1.02,4.0,0.0,1.0,18.0,0.8,137.53,4.63,11.3,6000.0,4.71,0.0,1\r\n80.0,1.01,2.0,3.0,1.0,53.0,1.8,137.53,4.63,9.6,7500.0,4.71,0.0,1\r\n70.0,1.005,4.0,0.0,1.0,56.0,3.8,111.0,2.5,11.2,6700.0,3.9,1.0,1\r\n80.0,1.01,2.0,0.0,1.0,26.0,1.4,137.53,4.63,11.6,7300.0,4.6,0.0,1\r\n90.0,1.015,3.0,0.0,1.0,25.0,1.1,142.0,3.2,12.2,7800.0,4.4,1.0,1\r\n70.0,1.01,0.0,0.0,1.0,54.0,24.0,104.0,4.0,12.4,8406.0,4.71,0.0,1\r\n76.0,1.015,2.0,4.0,1.0,31.0,1.1,137.53,4.63,12.4,6900.0,5.0,0.0,1\r\n100.0,1.015,3.0,0.0,1.0,60.0,1.9,137.53,4.63,10.8,9600.0,4.0,1.0,1\r\n90.0,1.02,2.0,0.0,0.0,107.0,7.2,114.0,3.7,9.5,12100.0,3.7,1.0,1\r\n60.0,1.01,2.0,4.0,1.0,55.0,4.0,137.53,4.63,9.4,8406.0,4.71,1.0,1\r\n70.0,1.01,3.0,0.0,0.0,60.0,2.7,131.0,4.2,10.8,4500.0,3.8,1.0,1\r\n70.0,1.015,3.0,1.0,1.0,72.0,2.1,138.0,5.8,9.7,12200.0,3.4,1.0,1\r\n70.0,1.02,1.0,0.0,1.0,86.0,4.6,135.0

In [101]:
df=pd.read_csv('new_model.csv')
df.head()

Bp     Sg   Al   Su  Rbc    Bu   Sc     Sod   Pot  Hemo    Wbcc  Rbcc  \
0  80.0  1.020  1.0  0.0  1.0  36.0  1.2  137.53  4.63  15.4  7800.0  5.20   
1  50.0  1.020  4.0  0.0  1.0  18.0  0.8  137.53  4.63  11.3  6000.0  4.71   
2  80.0  1.010  2.0  3.0  1.0  53.0  1.8  137.53  4.63   9.6  7500.0  4.71   
3  70.0  1.005  4.0  0.0  1.0  56.0  3.8  111.00  2.50  11.2  6700.0  3.90   
4  80.0  1.010  2.0  0.0  1.0  26.0  1.4  137.53  4.63  11.6  7300.0  4.60   

   Htn  Class  
0  1.0      1  
1  0.0      1  
2  0.0      1  
3  1.0      1  
4  0.0      1

In [102]:
x=df.drop(columns='Class')
y=df['Class']
scaler=StandardScaler()
scaler.fit(x)
standar=scaler.transform(x)

In [103]:
x=standar
y=df['Class']

# **PERCANTAGE SPLIT**

In [104]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state = 50)

In [105]:
SVM = svm.SVC(kernel = 'poly', degree=2, C=10, gamma=10)
SVM.fit(x_train,  y_train)
predictionSVM = SVM.predict(x_train)
trainingSVM = accuracy_score(predictionSVM ,y_train)
y_testSVM = SVM.predict(x_test)
test_accuracySVM = accuracy_score(y_test,y_testSVM)

ALR = LogisticRegression()
ALR.fit(x_train,  y_train)
predictionALR = ALR.predict(x_train)
trainingALR = accuracy_score(predictionALR ,y_train)
y_testALR = ALR.predict(x_test)
test_accuracyALR = accuracy_score(y_test,y_testALR)

C45 = DecisionTreeClassifier(random_state = 1)
C45.fit(x_train,  y_train)
predictionC45 = C45.predict(x_train)
trainingC45 = accuracy_score(predictionC45 ,y_train)
y_testC45 = C45.predict(x_test)
test_accuracyC45 = accuracy_score(y_test,y_testC45)

ENSEMBLE = StackingClassifier(estimators=[('SVM', SVM), ('ALR', ALR), ('C45', C45)])
ENSEMBLE.fit(x_train, y_train)
predictionENSEMBLE = ENSEMBLE.predict(x_train)
trainingENSEMBLE = accuracy_score(predictionENSEMBLE ,y_train)
y_testENSEMBLE = ENSEMBLE.predict(x_test)
test_accuracyENSEMBLE = accuracy_score(y_test,y_testENSEMBLE)

In [106]:
conf_matrixSVM = confusion_matrix(y_test, y_testSVM)
print("Confusion Matrix SVM:")
print(conf_matrixSVM)

conf_matrixALR = confusion_matrix(y_test, y_testALR)
print("Confusion Matrix ALR:")
print(conf_matrixALR)

conf_matrixC45 = confusion_matrix(y_test, y_testC45)
print("Confusion Matrix C4.5:")
print(conf_matrixC45)

conf_matrixENSEMBLE = confusion_matrix(y_test, y_testENSEMBLE)
print("Confusion Matrix ENSEMBLE:")
print(conf_matrixENSEMBLE)



Confusion Matrix SVM:
[[46  1]
 [19 94]]
Confusion Matrix ALR:
[[ 46   1]
 [  2 111]]
Confusion Matrix C4.5:
[[ 46   1]
 [  3 110]]
Confusion Matrix ENSEMBLE:
[[ 46   1]
 [  1 112]]


In [107]:
from sklearn.metrics import classification_report

print("\nclassification_report SVM:")
print(classification_report(y_test, y_testSVM))
print("\nclassification_report ALR:")
print(classification_report(y_test, y_testALR))
print("\nclassification_report C4.5:")
print(classification_report(y_test, y_testC45))
print("\nclassification_report ENSMBLE:")
print(classification_report(y_test, y_testENSEMBLE))

#print("Akurasi Data Training SVM: {:.2f}%". format(trainingSVM*100))
#print("Akurasi Data Training ALR: {:.2f}%". format(trainingALR*100))
#print("Akurasi Data Training C4.5: {:.2f}%". format(trainingC45*100))
#print("Akurasi Data Training Ensemble: {:.2f}%". format(trainingENSEMBLE*100))
#print("\n")
print("Akurasi Data Testing SVM: {:.2f}%". format(test_accuracySVM*100))
print("Akurasi Data Testing ALR: {:.2f}%". format(test_accuracyALR*100))
print("Akurasi Data Testing C4.5: {:.2f}%". format(test_accuracyC45*100))
print("Akurasi Data Testing Ensemble: {:.2f}%". format(test_accuracyENSEMBLE*100))



classification_report SVM:
              precision    recall  f1-score   support

           0       0.71      0.98      0.82        47
           1       0.99      0.83      0.90       113

    accuracy                           0.88       160
   macro avg       0.85      0.91      0.86       160
weighted avg       0.91      0.88      0.88       160


classification_report ALR:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97        47
           1       0.99      0.98      0.99       113

    accuracy                           0.98       160
   macro avg       0.97      0.98      0.98       160
weighted avg       0.98      0.98      0.98       160


classification_report C4.5:
              precision    recall  f1-score   support

           0       0.94      0.98      0.96        47
           1       0.99      0.97      0.98       113

    accuracy                           0.97       160
   macro avg       0.96      0.98      0.97

# **K-FOLD Cross Validassion**

In [120]:
kfold = KFold(n_splits=4, shuffle=True, random_state=55)
acc_scores = []
for train_index, test_index in kfold.split(x, y):
  x_train, x_test = x[train_index], x[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

  SVM = svm.SVC(kernel = 'poly', degree=2, C=10, gamma=10)
  SVM.fit(x_train,  y_train)
  predictionSVM = SVM.predict(x_train)
  trainingSVM = accuracy_score(predictionSVM ,y_train)
  y_testSVM = SVM.predict(x_test)
  test_accuracySVM = accuracy_score(y_test,y_testSVM)

  ALR = LogisticRegression()
  ALR.fit(x_train,  y_train)
  predictionALR = ALR.predict(x_train)
  trainingALR = accuracy_score(predictionALR ,y_train)
  y_testALR = ALR.predict(x_test)
  test_accuracyALR = accuracy_score(y_test,y_testALR)

  C45 = DecisionTreeClassifier(random_state = 1)
  C45.fit(x_train,  y_train)
  predictionC45 = C45.predict(x_train)
  trainingC45 = accuracy_score(predictionC45 ,y_train)
  y_testC45 = C45.predict(x_test)
  test_accuracyC45 = accuracy_score(y_test,y_testC45)

  ENSEMBLE = StackingClassifier(estimators=[('SVM', SVM), ('ALR', ALR), ('C45', C45)])
  ENSEMBLE.fit(x_train, y_train)
  predictionENSEMBLE = ENSEMBLE.predict(x_train)
  trainingENSEMBLE = accuracy_score(predictionENSEMBLE ,y_train)
  y_testENSEMBLE = ENSEMBLE.predict(x_test)
  test_accuracyENSEMBLE = accuracy_score(y_test,y_testENSEMBLE)

In [121]:
conf_matrixSVM = confusion_matrix(y_test, y_testSVM)
print("Confusion Matrix SVM:")
print(conf_matrixSVM)

conf_matrixALR = confusion_matrix(y_test, y_testALR)
print("Confusion Matrix ALR:")
print(conf_matrixALR)

conf_matrixC45 = confusion_matrix(y_test, y_testC45)
print("Confusion Matrix C4.5:")
print(conf_matrixC45)

conf_matrixENSEMBLE = confusion_matrix(y_test, y_testENSEMBLE)
print("Confusion Matrix ENSEMBLE:")
print(conf_matrixENSEMBLE)

Confusion Matrix SVM:
[[33  3]
 [ 8 56]]
Confusion Matrix ALR:
[[36  0]
 [ 2 62]]
Confusion Matrix C4.5:
[[35  1]
 [ 1 63]]
Confusion Matrix ENSEMBLE:
[[36  0]
 [ 1 63]]


In [122]:
print("\nclassification_report SVM:")
print(classification_report(y_test, y_testSVM))
print("\nclassification_report ALR:")
print(classification_report(y_test, y_testALR))
print("\nclassification_report C4.5:")
print(classification_report(y_test, y_testC45))
print("\nclassification_report ENSEMBLE:")
print(classification_report(y_test, y_testENSEMBLE))

#print("Akurasi Data Training SVM: {:.2f}%". format(trainingSVM*100))
#print("Akurasi Data Training ALR: {:.2f}%". format(trainingALR*100))
#print("Akurasi Data Training C4.5: {:.2f}%". format(trainingC45*100))
#print("Akurasi Data Training Ensemble: {:.2f}%". format(trainingENSEMBLE*100))
print("\n")
print("Akurasi Data Testing SVM: {:.2f}%". format(test_accuracySVM*100))
print("Akurasi Data Testing ALR: {:.2f}%". format(test_accuracyALR*100))
print("Akurasi Data Testing C4.5: {:.2f}%". format(test_accuracyC45*100))
print("Akurasi Data Testing Ensemble: {:.2f}%". format(test_accuracyENSEMBLE*100))


classification_report SVM:
              precision    recall  f1-score   support

           0       0.80      0.92      0.86        36
           1       0.95      0.88      0.91        64

    accuracy                           0.89       100
   macro avg       0.88      0.90      0.88       100
weighted avg       0.90      0.89      0.89       100


classification_report ALR:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        36
           1       1.00      0.97      0.98        64

    accuracy                           0.98       100
   macro avg       0.97      0.98      0.98       100
weighted avg       0.98      0.98      0.98       100


classification_report C4.5:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        36
           1       0.98      0.98      0.98        64

    accuracy                           0.98       100
   macro avg       0.98      0.98      0.98